.Dd June 26, 2026
.Dt FSXFSINFO 1
.Os
.Sh NAME
.Nm fsxfsinfo
.Nd determines information about a X File System (XFS) volume
.Sh SYNOPSIS
.Nm fsxfsinfo
.Op Fl B Ar bodyfile
.Op Fl E Ar inode_number
.Op Fl F Ar path
.Op Fl o Ar offset
.Op Fl dhHvV
.Ar source
.Sh DESCRIPTION
.Nm fsxfsinfo
is a utility to determine information about a X File System (XFS) volume
.Pp
.Nm fsxfsinfo
is part of the
.Nm libfsxfs
package.
.Nm libfsxfs
is a library to access the X File System (XFS) format
.Pp
.Ar source
is the source volume.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl B Ar bodyfile
output file system information as a bodyfile
.It Fl d
calculate a MD5 hash of a file entry to include in the bodyfile
.It Fl E Ar inode_number
show information about a specific inode or "all"
.It Fl F Ar path
show information about a specific file entry path
.It Fl h
shows this help
.It Fl H
shows the file system hierarchy
.It Fl o Ar offset
specify the volume offset in bytes
.It Fl v
verbose output to stderr
.It Fl V
print version
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
# fsxfsinfo xfs.raw
fsxfsinfo 20260621
.sp
X File System information:
.sp
Volume information:
	Format version			: 5
	Label				: xfs_test
	Compatible features		: 0x00000000
	Read-only compatible features	: 0x00000005
		(XFS_SB_FEAT_RO_COMPAT_FINOBT)
		(XFS_SB_FEAT_RO_COMPAT_REFLINK)
	Incompatible features		: 0x00000003
		(XFS_SB_FEAT_INCOMPAT_FTYPE)
		(XFS_SB_FEAT_INCOMPAT_SPINODES)
	Journal incompatible features	: 0x00000000
.sp
.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \
\-v is enabled.
Verbose and debug output are only printed when enabled at compilation.
.Sh SEE ALSO
.Xr fsxfsmount 1
.Sh AUTHORS
.An Joachim Metz <joachim.metz@gmail.com>
.Sh BUGS
Please report bugs of any kind on the project issue tracker: \
https://github.com/libyal/libfsxfs/issues
.Sh COPYRIGHT
Copyright (C) 2020-2026, Joachim Metz <joachim.metz@gmail.com>.
.sp
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A \
PARTICULAR PURPOSE.
